name: projetos
description: "Portal Administrativo de GestÃ£o da SEAE"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Pacotes principais do app
  firebase_core:
  firebase_auth:
  cloud_firestore:
  provider:
  google_fonts:
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.9.0
  flutter_svg: ^2.0.10
  flutter_modular: ^6.4.1
  web: ^1.1.1
  firebase_storage: ^12.1.0
  image_picker: ^1.1.2
  http: ^1.2.1
  mask_text_input_formatter: ^2.9.0
  fl_chart: ^0.68.0
  pdf: ^3.10.8
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/